dist: trusty

language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

addons:
  sonarcloud:
    organization: "nikonp"
    token: $SONAR_TOKEN

script:
  - qmake
  - make
  - ./tests/tests
  - sonar-scanner

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"

notifications:
  email: false
