dist: trusty

language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

addons:
  sonarcloud:
    organization: "nikonp"
    token:
      secure: $SONAR_TOKEN
  sonarqube:
      token: $SONAR_TOKEN

script:
  - qmake
  - make
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"

notifications:
  email: false
